name = "sapling/lifelike_characters_service"
version = "1.5.1"
license = "MIT"
repository = "https://github.com/Its-a-bit-random/Sapling"
authors = [ "Sebastian S <gramps@itsabitrandom.com>" ]
includes = ["pesde.toml", "README.md", "source/**" ]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "roblox"
lib = "source/init.luau"
build_files = ["source"]

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
